<a href="https://colab.research.google.com/github/huanyanwei/ai-projects/blob/main/Yan_Wei_ANLP_TF2_Toxic_Words_Text_Classification_Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 2.x

In [ ]:
!wget -qq https://www.dropbox.com/s/fz2d61pwgigtra7/toxic_words.zip
!unzip toxic_words.zip

!ls

Archive:  toxic_words.zip
  inflating: test_labels.csv         
  inflating: sample_submission.csv   
  inflating: test.csv                
  inflating: train.csv               
sample_data	       test.csv		toxic_words.zip
sample_submission.csv  test_labels.csv	train.csv


In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.style.use("ggplot")

import pandas as pd
import numpy as np

import tensorflow as tf

from tensorflow.keras.preprocessing import sequence
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence

from tensorflow.keras.optimizers import Adam

In [ ]:
# Aim to train the model using train_df
# Aim to fill in the classification of test_df 

train_df = pd.read_csv("./train.csv").fillna("blank")
test_df = pd.read_csv("./test.csv").fillna("blank")

In [ ]:
train_df.head(20)

id  ... identity_hate
0   0000997932d777bf  ...             0
1   000103f0d9cfb60f  ...             0
2   000113f07ec002fd  ...             0
3   0001b41b1c6bb37e  ...             0
4   0001d958c54c6e35  ...             0
5   00025465d4725e87  ...             0
6   0002bcb3da6cb337  ...             0
7   00031b1e95af7921  ...             0
8   00037261f536c51d  ...             0
9   00040093b2687caa  ...             0
10  0005300084f90edc  ...             0
11  00054a5e18b50dd4  ...             0
12  0005c987bdfc9d4b  ...             0
13  0006f16e4e9f292e  ...             0
14  00070ef96486d6f9  ...             0
15  00078f8ce7eb276d  ...             0
16  0007e25b2121310b  ...             0
17  000897889268bc93  ...             0
18  0009801bd85e5806  ...             0
19  0009eaea3325de8c  ...             0

[20 rows x 8 columns]

In [ ]:
train_df.shape

(159571, 8)

In [ ]:
X_train = train_df["comment_text"].values
y_train = train_df[["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"]].values

In [ ]:
y_train[0]

array([0, 0, 0, 0, 0, 0])

In [ ]:
X_train[0]

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

## **My attempt**
1. Create list of all the words
2. Tokenise the words
3. Pad each lines to be of the same length
4. Build and train model


In [ ]:
X_test = test_df["comment_text"].values

## y_test does not exist...

In [ ]:
# Split Labelled Training Data into 
    # X_train2, y_train2 --> training data (75%) and 
    # X_validn, y_validn --> validation data (25%)
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

from sklearn.model_selection import train_test_split

X_train2, X_validn, y_train2, y_validn = train_test_split(X_train, y_train, test_size=0.25)

# **Now I have 3 types of data:**


1.   train2 (X_train2, y_train2)
2.   valdn (X_validn, y_validn)
3.   test (X_test)



**Tokenizer**

In [ ]:
# create the tokenizer
t = Tokenizer()

# Get the total number of words from all datasets (i.e. train2, valdn and test)
all_comments = list (X_train2) + list(X_validn) + list(X_test)
print("There are a total of", len(all_comments), "comments in all of the data")

# fit the tokenizer on the documents
t.fit_on_texts(all_comments)

# summarize what was learned
total_num_of_words = len(t.word_counts)
print("There are a total of", total_num_of_words, "distinct words in all of the data")



There are a total of 312735 comments in all of the data
There are a total of 394787 distinct words in all of the data


In [ ]:
# re-create the tokenizer with only top 75% of the words
num_words = int(0.75*total_num_of_words)
t2 = Tokenizer(num_words = num_words)
t2.fit_on_texts(all_comments)

In [ ]:
encoded_train = t2.texts_to_sequences(X_train2)
encoded_valdn = t2.texts_to_sequences(X_validn)
#encoded_train[1]


**Padding Sequence**

In [ ]:
# pad sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_length = 50

padded_train = pad_sequences(encoded_train, maxlen=max_length, padding='pre')
padded_valdn = pad_sequences(encoded_valdn, maxlen=max_length, padding='pre')


In [ ]:
padded_valdn[1]

array([13691,     7,    43,    48,    88,     2,    16,    15,     1,
       21805,  2270,   174,     5,    19,   173,     1,   770,    50,
          63,    74,     7,    90,    11,     9,     7,   220,    56,
         460,    88,     2,    92,   481,  1238,   197,    51,    59,
         364,     2,   314,    73,     5,     7,   229,    79,     1,
         370,   936,    55,  1123,    95], dtype=int32)

In [ ]:
print(padded_valdn.shape)
print(y_train2.shape)
y_validn.shape


(39893, 50)
(119678, 6)


(39893, 6)

**Create Model**

Model based on Colab shared by lecturers.

In [ ]:
# Based on LSTM + Embedding Test Classification

from tensorflow.keras.models import Model
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input, Embedding
from tensorflow.keras.optimizers import RMSprop

Inp = Input(name='inputs',shape=[max_length])
x = Embedding(num_words,50,input_length=max_length)(Inp)
x = LSTM(64,name='LSTM_01')(x)
x = Dense(256,activation='relu',name='Dense_01')(x)
x = Dropout(0.5,name='Dropout')(x)
# Need to change output to 6 --> 6 types of output...
out = Dense(6,activation='sigmoid', name='output')(x)

In [ ]:
model = Model(inputs=Inp,outputs=out)
model.compile(loss='binary_crossentropy',optimizer=RMSprop(),metrics=['accuracy'])

model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, 50)]              0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 50, 50)            14804500  
_________________________________________________________________
LSTM_01 (LSTM)               (None, 64)                29440     
_________________________________________________________________
Dense_01 (Dense)             (None, 256)               16640     
_________________________________________________________________
Dropout (Dropout)            (None, 256)               0         
_________________________________________________________________
output (Dense)               (None, 6)                 1542      
Total params: 14,852,122
Trainable params: 14,852,122
Non-trainable params: 0
_______________________________________________

**Start Training**

In [ ]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss',min_delta=0.0001)

In [ ]:
model.fit(padded_train,y_train2,
          batch_size=128,
          epochs=10,
          validation_data=(padded_valdn, y_validn),
          callbacks=[early_stop])

Epoch 1/10
935/935 [==============================] - 74s 79ms/step - loss: 0.0798 - accuracy: 0.9410 - val_loss: 0.0587 - val_accuracy: 0.9942
Epoch 2/10
935/935 [==============================] - 73s 78ms/step - loss: 0.0550 - accuracy: 0.9941 - val_loss: 0.0567 - val_accuracy: 0.9942
Epoch 3/10
935/935 [==============================] - 72s 77ms/step - loss: 0.0511 - accuracy: 0.9940 - val_loss: 0.0546 - val_accuracy: 0.9942
Epoch 4/10
935/935 [==============================] - 72s 77ms/step - loss: 0.0477 - accuracy: 0.9940 - val_loss: 0.0600 - val_accuracy: 0.9942


Encode and Pad the Test Data!

In [ ]:
encoded_test = t2.texts_to_sequences(X_test)
padded_test = pad_sequences(encoded_test, maxlen=max_length, padding='pre')
print(padded_test[0])

[  1487 251803    578   5873      5     94      6      2   3771     30
    339      6    742  34978     37   4884    724      8     35   4220
     10   1205    653    400    476  17275      9    227     15    154
      5  20164      8    247  23359     48   4329     52     24      4
   2108    155   2432    578   2429     94    218    143    490     85]


Send test data into model to predict...

In [ ]:
prediction = model.predict(padded_test)
prediction[0]

array([0.99459165, 0.34296796, 0.95605326, 0.04550057, 0.8812876 ,
       0.23515476], dtype=float32)

In [ ]:
# To round the output to 0/1
round_predictions= np.round(prediction)
results_df= pd.concat([test_df, pd.DataFrame(round_predictions, columns= ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"])], axis=1)

results_df.head(50)

id  ... identity_hate
0   00001cee341fdb12  ...           0.0
1   0000247867823ef7  ...           0.0
2   00013b17ad220c46  ...           0.0
3   00017563c3f7919a  ...           0.0
4   00017695ad8997eb  ...           0.0
5   0001ea8717f6de06  ...           0.0
6   00024115d4cbde0f  ...           0.0
7   000247e83dcc1211  ...           0.0
8   00025358d4737918  ...           0.0
9   00026d1092fe71cc  ...           0.0
10  0002eadc3b301559  ...           0.0
11  0002f87b16116a7f  ...           0.0
12  0003806b11932181  ...           0.0
13  0003e1cccfd5a40a  ...           0.0
14  00059ace3e3e9a53  ...           0.0
15  000634272d0d44eb  ...           0.0
16  000663aff0fffc80  ...           0.0
17  000689dd34e20979  ...           0.0
18  000834769115370c  ...           0.0
19  000844b52dee5f3f  ...           0.0
20  00084da5d4ead7aa  ...           0.0
21  00091c35fa9d0465  ...           0.0
22  000968ce11f5ee34  ...           0.0
23  0009734200a85047  ...           0.0
24  00097b6214686db5  ...           0.0
25  0009aef4bd9e1697  ...           0.0
26  000a02d807ae0254  ...           0.0
27  000a6c6d4e89b9bc  ...           0.0
28  000bafe2080bba82  ...           0.0
29  000bf0a9894b2807  ...           0.0
30  000c50dceb1eed2b  ...           0.0
31  000c9b92318552d1  ...           0.0
32  000ce41d86f2b886  ...           0.0
33  000cf60dbaed8c02  ...           0.0
34  000d4f120d5a7303  ...           0.0
35  000d60becb7d1a67  ...           0.0
36  000fc381d4895598  ...           0.0
37  000ff37cf57ab537  ...           0.0
38  001068b809feee6b  ...           0.0
39  0011c58fcfd6bf91  ...           0.0
40  0011cefc680993ba  ...           0.0
41  0011ef6aa33d42e6  ...           0.0
42  0012706ac77a7b37  ...           0.0
43  0012bb72f20ae971  ...           0.0
44  0012bbcbd6958302  ...           0.0
45  00137446b1aec28c  ...           0.0
46  0013a435effa29bd  ...           0.0
47  0013be435187e84f  ...           0.0
48  0013fed3aeae76b7  ...           0.0
49  001411adf8f1dd82  ...           0.0

[50 rows x 8 columns]

----------------------------------- **End of Challenge ** ----------------------------------------

**Addition**

Actually did not need to manually split the training data into train2 & validation... model can auto split the data for validation. 

To try again without splitting the data manually and using a differnet model...

In [ ]:
# Experimenting with a different model

from tensorflow.keras.models import Model
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input, Embedding, GlobalMaxPooling1D
from tensorflow.keras.optimizers import RMSprop

Inp = Input(name='inputs',shape=[max_length])
x = Embedding(num_words,50,input_length=max_length)(Inp)
x = GlobalMaxPooling1D()(x)
x = Dropout(0.5,name='Dropout')(x)
# Need to change output to 6 --> 6 types of output...
out = Dense(6,activation='sigmoid', name='output')(x)

In [ ]:
model2 = Model(inputs=Inp,outputs=out)
# Change Optimiser
model2.compile(loss='binary_crossentropy',optimizer=Adam(0.01),metrics=['accuracy'])

model2.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
inputs (InputLayer)          [(None, 50)]              0         
_________________________________________________________________
embedding_2 (Embedding)      (None, 50, 50)            14804500  
_________________________________________________________________
global_max_pooling1d (Global (None, 50)                0         
_________________________________________________________________
Dropout (Dropout)            (None, 50)                0         
_________________________________________________________________
output (Dense)               (None, 6)                 306       
Total params: 14,804,806
Trainable params: 14,804,806
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# Create the same padded train data
# Try "post" padding instead...
encoded_full_train = t2.texts_to_sequences(X_train)
padded_train = pad_sequences(encoded_train, maxlen=max_length, padding='post')

# change early_stop 0.0001 --> 0.001
early_stop = EarlyStopping(monitor='val_loss',min_delta=0.001)

# Reduce the number of epochs to 3 as the previous training was completed within 4
model2.fit(X_train,y_train,
          batch_size=128,
          epochs=3,
          validation_split=0.2,
          callbacks=[early_stop])

Epoch 1/3


In [ ]:
prediction = model2.predict(padded_test)
prediction[0]

In [ ]:
round_predictions= np.round(prediction)
results_df= pd.concat([test_df, pd.DataFrame(round_predictions, columns= ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate"])], axis=1)

results_df.head(50)